"""Auth package exports."""

from app.core.auth.passwords import ADMIN_EMAIL, AuthError, MIN_PASSWORD_LEN, hash_password, verify_password
from app.core.auth.service import (
    INVITE_DAYS,
    PASSWORD_RESET_DAYS,
    SESSION_COOKIE,
    SESSION_DAYS,
    EMAIL_CHANGE_HOURS,
    EMAIL_VERIFY_HOURS,
    authenticate,
    cancel_email_change,
    cancel_email_change_by_token,
    change_password,
    claim_invite,
    claim_password_reset,
    confirm_email_change,
    create_email_verification,
    create_incomplete_user,
    create_invite,
    create_password_reset,
    create_session,
    get_admin,
    get_pending_email_change,
    get_user_by_email,
    get_user_for_token,
    is_email_verified,
    mask_email,
    private_user_dict,
    public_user_dict,
    register_player,
    request_email_change,
    revoke_session,
    upsert_admin_password,
    verify_email,
)

# Back-compat alias used by older scripts/docs
ADMIN_USERNAME = "admin"

__all__ = [
    "ADMIN_EMAIL",
    "ADMIN_USERNAME",
    "AuthError",
    "INVITE_DAYS",
    "EMAIL_CHANGE_HOURS",
    "EMAIL_VERIFY_HOURS",
    "MIN_PASSWORD_LEN",
    "PASSWORD_RESET_DAYS",
    "SESSION_COOKIE",
    "SESSION_DAYS",
    "authenticate",
    "cancel_email_change",
    "cancel_email_change_by_token",
    "change_password",
    "claim_invite",
    "claim_password_reset",
    "confirm_email_change",
    "create_email_verification",
    "create_incomplete_user",
    "create_invite",
    "create_password_reset",
    "create_session",
    "get_admin",
    "get_pending_email_change",
    "get_user_by_email",
    "get_user_for_token",
    "is_email_verified",
    "hash_password",
    "mask_email",
    "private_user_dict",
    "public_user_dict",
    "register_player",
    "request_email_change",
    "revoke_session",
    "upsert_admin_password",
    "verify_email",
    "verify_password",
]
